import matplotlib.pyplot as plt

# Take input points
x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

# Calculate differences
dx = abs(x2 - x1)
dy = abs(y2 - y1)

# Determine direction
sx = 1 if x2 > x1 else -1
sy = 1 if y2 > y1 else -1

# Initial decision parameter
p = 2 * dy - dx

x = x1
y = y1

points_x = []
points_y = []

# Bresenham's Algorithm
if dx >= dy:
    for i in range(dx + 1):
        points_x.append(x)
        points_y.append(y)

        if p < 0:
            p = p + 2 * dy
        else:
            y = y + sy
            p = p + 2 * dy - 2 * dx

        x = x + sx

else:
    p = 2 * dx - dy

    for i in range(dy + 1):
        points_x.append(x)
        points_y.append(y)

        if p < 0:
            p = p + 2 * dx
        else:
            x = x + sx
            p = p + 2 * dx - 2 * dy

        y = y + sy

# Display generated points
print("\nPoints generated by Bresenham's Algorithm:")

for i in range(len(points_x)):
    print(f"({points_x[i]}, {points_y[i]})")

# Plot the line
plt.plot(points_x, points_y, marker='o')
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Bresenham's Line Drawing Algorithm")
plt.grid(True)
plt.axis("equal")
plt.show()
