import matplotlib.pyplot as plt

# Take input points from the user
x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

# Calculate differences
dx = x2 - x1
dy = y2 - y1

# Number of steps
steps = max(abs(dx), abs(dy))

# Calculate increments
x_inc = dx / steps
y_inc = dy / steps

# Starting point
x = x1
y = y1

points_x = []
points_y = []

# DDA Algorithm
for i in range(steps + 1):
    points_x.append(round(x))
    points_y.append(round(y))

    x += x_inc
    y += y_inc

# Display the points
print("\nPoints generated by DDA:")
for i in range(len(points_x)):
    print(f"({points_x[i]}, {points_y[i]})")

# Plot the line
plt.plot(points_x, points_y, marker='o')
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("DDA Line Drawing Algorithm")
plt.grid(True)
plt.axis("equal")
plt.show()